### ISSUE TITLE
Witchaven 1/2 + BuildGDX Crash on Exit

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#702]
### Game

Witchaven 1/2

### Engine

BuildGDX

### Linux Distribution

NixOS + Flatpak

### Luxtorpeda Version

53

### Bug description

When exiting the game it crashes and leaves behind a broken window.

### Steps To Reproduce

Exit the game using the in-game menu.

### Expected Behavior

The game should exit cleanly.

### Additional Context

After the window hangs, the game can be forced closed by clicking stop on Steam.

### Relevant log output

```shell
java.io.FileNotFoundException
        at ru.m210projects.Witchaven.Screens.CutsceneScreen$SMKMovieFile.<init>(CutsceneScreen.java:47)
        at ru.m210projects.Witchaven.Screens.CutsceneScreen.GetFile(CutsceneScreen.java:150)
        at ru.m210projects.Build.Pattern.ScreenAdapters.MovieScreen.open(MovieScreen.java:94)
        at ru.m210projects.Witchaven.Screens.CutsceneScreen.init(CutsceneScreen.java:139)
        at ru.m210projects.Witchaven.Main.show(Main.java:441)
        at ru.m210projects.Build.Pattern.ScreenAdapters.InitScreen.render(InitScreen.java:280)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at ru.m210projects.Build.Pattern.BuildGame.render(BuildGame.java:130)
        at ru.m210projects.Build.Architecture.BuildApplication.mainLoop(BuildApplication.java:137)
        at ru.m210projects.Build.Architecture.BuildApplication.access$000(BuildApplication.java:39)
        at ru.m210projects.Build.Architecture.BuildApplication$1.run(BuildApplication.java:92)
```

**Comment by d10sfan** [comment]
I am able to replicate this. This appears to be an issue with the upstream engine as this is just using the built version from the BuildGDX project. I'm not sure as to a resolution as this time.

**Comment by d10sfan** [comment]
@JoshuaFern 

I attempted to get some help from upstream and have done some stuff myself as well, to no avail. For now, I've removed BuildGDX as an engine, but will add it back if this gets resolved. In the meantime, Witchaven games are now supported by dosbox-staging. If  BuildGDX works again, I'll have both as engine choices for those games.
